http:
  routers:
    paas-cf32693b-62b5-4e6f-b1e2-1a1057112190:
      rule: "Host(`web-web-landing.localhost`)"
      entryPoints:
        - web
      middlewares:
        - paas-lb-chain@file
      service: paas-cf32693b-62b5-4e6f-b1e2-1a1057112190
  services:
    paas-cf32693b-62b5-4e6f-b1e2-1a1057112190:
      loadBalancer:
        passHostHeader: true
        serversTransport: paas-default-lb@file
        responseForwarding:
          flushInterval: 100ms
        servers:
          - url: "http://paas-6386ea43-cf32693b-v2-1:3000"
          - url: "http://paas-6386ea43-cf32693b-v2-2:3000"
